{% set name = "tsnecuda" %}
{% set version = "0.1.1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_url: https://github.com/CannyLab/tsne-cuda.git
  git_rev: HEAD
  
requirements:
  build:
    - python
    - gcc_49
    - cmake
    - cudatoolkit >=8.0
    - setuptools
    - openblas
  host:
    - python
    - openblas
    - setuptools
    - cudatoolkit >=8.0
    - numpy >=1.14.1
  run:
    - python
    - openblas
    - cudatoolkit >=8.0
    - numpy >=1.14.1

about:
  home: https://github.com/CannyLab/tsne-cuda
  license: LICENSE.txt
  license_family: BSD
  license_file: ''
  summary: CUDA Implementation of T-SNE with Python bindings
  description: "===========\ntsnecuda\n===========\n\ntsnecuda provides an optimized CUDA implementation of the T-SNE algorithm by L Van der Maaten. tsnecuda is able to compute the T-SNE of large numbers\
    \ of points up to 1200 times faster than other leading libraries, and provides simple python bindings with a SKLearn style interface::\n\n    #!/usr/bin/env python\n\n    from tsnecuda import TSNE\n\
    \    embeddedX = TSNE(n_components=2).fit_transform(X)\n\nFor more information, check out the repository at https://github.com/rmrao/tsne-cuda. \n\n\n"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
